from pathlib import Path


class Generator:

    @staticmethod
    def create_directory(path):
        directory = Path(path)
        directory.mkdir(parents=True, exist_ok=True)
        print(f"[DIR] {directory}")

    @staticmethod
    def create_file(path, content=""):
        file = Path(path)

        file.parent.mkdir(parents=True, exist_ok=True)

        if not file.exists():
            file.write_text(content)

        print(f"[FILE] {file}")

    @staticmethod
    def create_pack(name):

        Generator.create_directory(f"packs/{name}")

        Generator.create_file(
            f"packs/{name}/README.md",
            f"# {name}\n\nGenerated by PRiZM Installer\n"
        )

        Generator.create_file(
            f"packs/{name}/manifest.json",
            '{\n    "name": "' + name + '"\n}\n'
        )
